# 初體驗

In [1]:
1+1

2

In [2]:
var c = 1
var d = 2
print(c + d)

3

In [6]:
d * 2

4

In [4]:
// 變數需要宣告
a = 1
b = 2
a + b

In [5]:
var str1 = "Hello kotlin"
str1

Hello kotlin

In [7]:
var mylist = listOf(1,2,3)
println(mylist)

[1, 2, 3]


In [40]:
import java.util.Random
var rand = Random()
rand.setSeed(12)
for(i in 1..3){
    println(rand.nextFloat())
}


0.7298928
0.059827566
0.27506912


# [Kotlin-Jupyter-Kernel](https://pypi.org/project/kotlin-jupyter-kernel/) 介紹

## command
* :help
* :classpath

## Magics
* %use
* %trackClasspath
* %trackExecution
* %output

## Default repositories
* Bintray JCenter (https://jcenter.bintray.com/)
* Maven Central (https://repo.maven.apache.org/maven2)
* JitPack (https://jitpack.io/)

## Import library
* using annotations
* using magics command (%use)
* Note: Dependencies 的cache 預設路徑： ~/.ivy2/cache，當cache檔損壞時，刪除該檔案並重新啟動kerne

In [8]:
@file:Repository("https://jcenter.bintray.com/")
@file:DependsOn("com.beust:klaxon:5.2")
import com.beust.klaxon.*

In [9]:
Klaxon()

com.beust.klaxon.Klaxon@68ac9ec5

* 非預設的repository

In [1]:
@file:Repository("https://kotlin.bintray.com/kotlin-numpy")
@file:DependsOn("org.jetbrains:kotlin-numpy:0.1.4")
import org.jetbrains.numkt.core.*
import org.jetbrains.numkt.math.*
import org.jetbrains.numkt.*

In [19]:
val a = arange(15).reshape(3, 5) // KtNDArray<Int>([[ 0,  1,  2,  3,  4],
                                                 // [ 5,  6,  7,  8,  9],
                                                 // [10, 11, 12, 13, 14]]

println(a.shape.contentEquals(intArrayOf(3, 5))) // true
println(a.ndim == 2)                             // true
println(a.dtype)                                 // class java.lang.Integer

// create an array of ints, we square each element and the shape to (3, 5) 
val b = (arange(15) `**` 2).reshape(3, 5)
println("a array: \n$a")
println("b array: \n$b")
// c is the product of a and b, element-wise
val c = a * b
println("a * b result:\n $c")
// Output:
// [[   0    1    8   27   64]
//  [ 125  216  343  512  729]
//  [1000 1331 1728 2197 2744]]


true
true
class java.lang.Integer
a array: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
b array: 
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]]
a * b result:
 [[   0    1    8   27   64]
 [ 125  216  343  512  729]
 [1000 1331 1728 2197 2744]]


In [12]:
Math.pow(5.0,2.0)

25.0

* 一個library

In [12]:
%use klaxon

* 多個library

In [16]:
%use klaxon, lets-plot

* 指定library版本

In [17]:
%use klaxon(5.2)

* 多個library，僅部份指定版本 

In [18]:
%use klaxon(5.2), lets-plot

* 指定library下各屬性之版本

In [ ]:
%use spark(scala=2.11.10, spark=2.4.2)